### ISSUE TITLE
Can not attach screenshot file in PDF Report

### ISSUE THREAD

**Issue by anhtester** [grasshopper7/extent-pdf-report#7]
![image](https://user-images.githubusercontent.com/87883620/202400500-85eb8377-9193-42a3-9ed4-949c28007910.png)

**Comment by grasshopper7** [comment]
Have you tried with the sample project? Can you add the relevant code? Thx

**Comment by anhtester** [comment]
> Have you tried with the sample project? Can you add the relevant code? Thx

My Project: https://github.com/anhtester/AutomationFrameworkSelenium

Thank you.
